#!/bin/sh

printf "\n%s\n" "Pre-push hook activated."

printf "\n%s\n" "Running gofmt..."
unformatted=$(gofmt -w .)

if [ -n "$unformatted" ]; then
    printf "%s\n" "These files are not gofmt-formatted:"
    printf "%s\n" "$unformatted"
    printf "\n%s\n" "Please run: gofmt -w ."
    exit 1
else
    printf "%s\n" "All files are properly formatted."
fi


printf "\n%s\n" "Running golangci-lint..."
if command -v golangci-lint >/dev/null 2>&1; then
    golangci-lint run
    lint_status=$?
else
    printf "%s\n" "golangci-lint not installed. Skipping linting."
    lint_status=0
fi


printf "\n%s\n" "Executing tests..."
start_tests=$(date +%s)

go test ./... -coverprofile=coverage.out
test_status=$?

end_tests=$(date +%s)
printf "\nTesting completed in %s seconds.\n" "$(($end_tests-$start_tests))"


printf "\n%s\n" "Checking coverage..."

if [ -f coverage.out ]; then
    total_cov=$(go tool cover -func=coverage.out | grep total | awk '{print substr($3, 1, length($3)-1)}')
    total_cov_int=$(printf "%.0f" "$total_cov")

    min_cov=100

    printf "Total coverage: %s%% (required: %s%%)\n" "$total_cov" "$min_cov"

    if [ "$total_cov_int" -lt "$min_cov" ]; then
        printf "\n%s\n" "Code coverage test failed."

        printf "\n%s\n" "Uncovered lines:"
        awk '$3 == 0 {print $1 " (" $2 ") — NOT COVERED"}' coverage.out
        printf "\n"

        coverage_status=1
    else
        coverage_status=0
    fi
else
    printf "%s\n" "coverage.out missing. Cannot evaluate coverage."
    coverage_status=1
fi

hook_status=0

if [ "$test_status" -ne 0 ]; then
    hook_status=$test_status
    printf "%s\n" "There are failed tests."
fi

if [ "$coverage_status" -ne 0 ]; then
    hook_status=$coverage_status
fi

if [ "$lint_status" -ne 0 ]; then
    hook_status=$lint_status
    printf "%s\n" "Linting errors found."
fi

rm coverage.out
printf "Success! No errors found!"
exit $hook_status
